const gate = document.getElementById('manager-gate');
const dashboard = document.getElementById('manager-dashboard');
const ordersEl = document.getElementById('manager-orders');
const statsEl = document.getElementById('manager-stats');
const statusEl = document.getElementById('manager-status');
const searchInput = document.getElementById('manager-search');
let orders = [];
let filter = 'all';
const escape = value => String(value || '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char]));
const date = value => value ? new Intl.DateTimeFormat('ru-RU',{ day:'numeric', month:'short', year:'numeric', hour:'2-digit', minute:'2-digit' }).format(new Date(value)) : '—';
const statusLabel = status => ({ draft:'Новая заявка', pending_review:'Проверка документов', awaiting_payment:'Ожидает оплаты', payment_review:'Проверка оплаты', confirmed:'Оплата подтверждена', awaiting_pickup:'Готовится к выдаче', issued:'Выдана', in_use:'Активна', return_requested:'Возврат', returned:'Проверка возврата', completed:'Завершена', cancelled:'Отменена', rejected:'Отклонена' }[status] || status || 'Новая');
const docLabel = kind => ({ identity:'Документ', selfie:'Селфи', supporting:'Доп. документ' }[kind] || 'Документ');
const nextAction = status => ({ awaiting_payment:{ next:'confirmed', label:'Оплата проверена' }, confirmed:{ next:'awaiting_pickup', label:'Ноутбук подготовлен' }, awaiting_pickup:{ next:'issued', label:'Отметить выдачу' }, issued:{ next:'in_use', label:'Подтвердить получение' }, return_requested:{ next:'returned', label:'Техника получена' }, returned:{ next:'completed', label:'Завершить аренду' } })[status] || null;
async function api(method = 'GET', payload) { const response = await fetch('/api/manager', { method, credentials:'same-origin', cache:'no-store', headers:payload ? { 'content-type':'application/json' } : {}, body:payload ? JSON.stringify(payload) : undefined }); const data = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(data.error || 'Не удалось загрузить панель.'); error.status = response.status; throw error; } return data; }
function visibleOrders() { const query = String(searchInput?.value || '').trim().toLowerCase(); return orders.filter(order => { const matchesSearch = !query || `${order.id} ${order.customer_name} ${order.customer_phone} ${order.laptop_title}`.toLowerCase().includes(query); if (!matchesSearch) return false; if (filter === 'new') return ['draft','pending_review','awaiting_payment','payment_review','confirmed','awaiting_pickup'].includes(order.status); if (filter === 'documents') return order.documents.some(document => document.status === 'pending_review'); if (filter === 'active') return ['issued','in_use','return_requested','returned'].includes(order.status); if (filter === 'closed') return ['completed','cancelled','rejected'].includes(order.status); return true; }); }
function render() { const list = visibleOrders(); const pendingDocs = orders.reduce((total, order) => total + order.documents.filter(document => document.status === 'pending_review').length, 0); const active = orders.filter(order => ['issued','in_use','return_requested','returned'].includes(order.status)).length; const fresh = orders.filter(order => ['draft','pending_review','awaiting_payment','payment_review','confirmed','awaiting_pickup'].includes(order.status)).length; statsEl.innerHTML = [[orders.length,'Всего заявок'],[fresh,'В работе'],[pendingDocs,'Документы на проверке'],[active,'Активные аренды']].map(([value,label]) => `<div class="manager-stat"><span>${label}</span><strong>${value}</strong></div>`).join(''); ordersEl.innerHTML = list.length ? list.map(order => { const action = nextAction(order.status); return `<article class="manager-order"><div class="manager-order-top"><div><h2>${escape(order.laptop_title)}</h2><p>Заявка ${escape(String(order.id).slice(0,8).toUpperCase())} · ${escape(order.customer_name || 'Клиент не указал имя')}</p></div><span class="manager-status-pill">${escape(statusLabel(order.status))}</span></div><div class="manager-order-grid"><div><span>Клиент</span><strong>${escape(order.customer_phone || '—')}</strong></div><div><span>Аренда</span><strong>${date(order.rental_start_date)} — ${date(order.rental_end_date)}</strong></div><div><span>Получение</span><strong>${escape(order.delivery_type || '—')}</strong></div><div><span>Сумма</span><strong>${Number(order.total_amount || 0).toLocaleString('ru-RU')} сом</strong></div></div><section class="manager-section"><h3>Документы</h3><div class="manager-docs">${order.documents.length ? order.documents.map(document => `<div class="manager-doc"><span>${docLabel(document.kind)} · ${document.status === 'pending_review' ? 'на проверке' : document.status}</span>${document.view_url ? `<a href="${escape(document.view_url)}" target="_blank" rel="noopener noreferrer">Открыть</a>` : ''}${document.status === 'pending_review' ? `<button class="accept" data-document="${document.id}" data-status="accepted">Принять</button><button class="reject" data-document="${document.id}" data-status="rejected">Отклонить</button>` : ''}</div>`).join('') : '<span class="manager-empty">Документы ещё не загружены</span>'}</div></section>${order.requests.length ? `<section class="manager-section"><h3>Запросы клиента</h3><div class="manager-requests">${order.requests.map(request => `<div class="manager-request">${escape(request.kind)} · ${escape(request.status)}${request.customer_message ? ` · ${escape(request.customer_message)}` : ''}</div>`).join('')}</div></section>` : ''}${action ? `<div class="manager-actions"><button data-order-action="advance" data-order="${order.id}" data-next-status="${action.next}">${action.label}</button></div>` : ''}</article>`; }).join('') : '<div class="manager-empty">По этому фильтру заявок нет.</div>'; }
async function load() { statusEl.textContent = 'Загружаем заявки…'; try { const data = await api(); orders = data.orders || []; gate.hidden = true; dashboard.hidden = false; statusEl.textContent = `Обновлено: ${new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date())}`; render(); } catch (error) { dashboard.hidden = true; gate.hidden = error.status === 401; statusEl.textContent = error.status === 401 ? '' : error.message; } }
document.getElementById('manager-refresh').addEventListener('click', load);
document.querySelector('.manager-filters').addEventListener('click', event => { const button = event.target.closest('[data-filter]'); if (!button) return; filter = button.dataset.filter; document.querySelectorAll('[data-filter]').forEach(item => item.classList.toggle('is-active', item === button)); render(); });
searchInput?.addEventListener('input', render);
ordersEl.addEventListener('click', async event => { const button = event.target.closest('[data-document], [data-order-action]'); if (!button) return; button.disabled = true; try { if (button.dataset.document) await api('POST', { action:'review_document', documentId:button.dataset.document, status:button.dataset.status }); else await api('POST', { action:'advance_order', orderId:button.dataset.order, nextStatus:button.dataset.nextStatus }); await load(); } catch (error) { statusEl.textContent = error.message; button.disabled = false; } });
load();
